### ISSUE TITLE
missing hosts.txt

### ISSUE THREAD

**Issue by everslick** [clifflu/remedy#1]
forgot to commit?

**Comment by everslick** [comment]
ah, ic you mean the windows hosts file. nevermind.

**Comment by clifflu** [comment]
Hi @everslick, 

It's not the windows hosts file, but a file with IP's, one per line, that is passed to `remedy.py`.

**Comment by everslick** [comment]
But then, what file are you referring to in the README.md? -> See hosts.txt as example

first i thought you provided the example in hosts, but that is empty, so i figured you meant the hosts file of windows (is it still called hosts.txt? I've no idea)

so my first assumption was right?

**Comment by clifflu** [comment]
You're right :) Should at least keep some examples in `hosts` during the cleanup.
I'll try improve the project after work, although it's released with permission.

**Comment by everslick** [comment]
I think it's not relevant anymore. Closing...
